### ISSUE TITLE
Make neighbor parameter in duts file optional 

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#297]
**Is your feature request related to a problem? Please describe.**
Neighbor parameter in duts file required.  Vane fails if this is missing.   
```
duts:
- mgmt_ip: <ip address>
  name: <dut name>
  # Required
  neighbors:
  - neighborDevice: <dut neighbor name>
    neighborPort: <neighbor port>
    port: <local port>
```

**Describe the solution you'd like**
The neighbor parameter should be optional and not cause a failure.  This information can be inputted in other ways like through AVD structured data.

**Describe alternatives you've considered**
None

**Additional context**
None
