### ISSUE TITLE
Dynamically create DUTs file

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#356]
**Is your feature request related to a problem? Please describe.**
In NRFU testing DUTs file needs to created dynamically based on user input

**Describe the solution you'd like**
Nrfu_client module will use the input data from earlier steps to create the DUTs data structure.  

If CVP was used as a source of truth for DUTs data, the following template will be used to create DUTs information:

```
duts: 
# 1 entry per DUT discovered from CVP
- mgmt_ip: <CVP API: ipAddress>
  name: <CVP API: hostname>
  neighbors: []
  password: <user inputted>
  transport: https
  username: <user inputted>
  role: unknown
```

If CVP was NOT used as a source of truth for DUTs data, the following template will be used to create DUTs information:

```
duts: 
# 1 entry per IP address from device list file
- mgmt_ip: <IP Address>
  name: <IP Address >
  neighbors: []
  password: <user inputted>
  transport: https
  username: <user inputted>
  role: unknown
```

Nrfu_client module will use DUTs data structure to write file duts.yml.  Tests_client module will use duts.yml file in normal operations and no modification should be needed.

**Describe alternatives you've considered**
None

**Additional context**
None
